name: Publish To NPM

on:
  workflow_run:
    workflows: ["Tag"]  # The name of the workflow to watch
    types:
      - completed

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                persist-credentials: false

            - name: Publish to npm
              uses: JS-DevTools/npm-publish@v3
              with:
                token: ${{ secrets.NPM_TOKEN }}

